apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra    ## this name will be used as the seed ip in another cluster
spec:
  clusterIP: None
  ports:
    - port: 9042
      port: 7000        ## we added this for intra-node communication
  selector:
    app: cassandra
